namespace API.Models;

public class ApiResult
{
    /// <summary>
    /// Represents the intermediate or contextual insights generated by the local LLM (Large Language Model)
    /// during the processing of a SQL query request.
    /// This property typically contains thoughts or reasoning that the model used to arrive at the final SQL query.
    /// </summary>
    public string Thoughts { get; set; }

    /// <summary>
    /// Gets or sets the SQL query generated from a natural language input or response.
    /// This property is used to store the parsed SQL query which can be executed against a database.
    /// </summary>
    public string SqlQuery { get; set; }

    /// <summary>
    /// Represents the result returned from executing an SQL query generated by the local LLM (Large Language Model).
    /// This property typically contains the raw execution output of the query run against a database.
    /// </summary>
    public string DbResult { get; set; }
}